# Generated by Django 3.2.3 on 2021-06-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imageessssss',
            new_name='image',
        ),
    ]
